# Generated by Django 5.0.4 on 2024-04-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_log_tipus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='tipus',
            field=models.CharField(choices=[('INFO', 'Informació'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('FATAL', 'Fatal')], default='', max_length=10),
        ),
    ]
