# Generated by Django 5.0.4 on 2024-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_log_tipus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='tipus',
            field=models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('FATAL', 'Fatal')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='usuari',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
