# Generated by Django 5.0.4 on 2024-04-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_catalog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='imatge',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='imatgecatalog',
            name='imatge',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='imatge',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
