# Generated by Django 5.0.4 on 2024-04-24 03:34

import app.managers
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_catalog_imatge_alter_imatgecatalog_imatge_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuari',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='usuari',
            managers=[
                ('objects', app.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuari',
            name='cognoms',
        ),
        migrations.RemoveField(
            model_name='usuari',
            name='contrasenya_cifrada',
        ),
        migrations.AddField(
            model_name='usuari',
            name='cognom',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usuari',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='biblioteca_user_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='password',
            field=models.CharField(default='vite', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuari',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='biblioteca_user_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='username',
            field=models.CharField(default='vite', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuari',
            name='data_naixement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='imatge',
            field=models.ImageField(blank=True, null=True, upload_to='imatges/'),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='nom',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
