# Generated by Django 5.0.4 on 2024-05-06 15:59

import app.managers
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField()),
                ('imatge', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuari', models.CharField(blank=True, max_length=100, null=True)),
                ('accio', models.CharField(max_length=100)),
                ('data_accio', models.DateTimeField(auto_now_add=True)),
                ('tipus', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('FATAL', 'Fatal')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipusMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('llibre', 'Llibre'), ('CD', 'CD'), ('DVD', 'DVD'), ('BR', 'Blu-ray'), ('dispositiu', 'Dispositiu')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BR',
            fields=[
                ('catalog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.catalog')),
                ('productora', models.CharField(max_length=100)),
                ('duracio', models.IntegerField()),
            ],
            bases=('app.catalog',),
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('catalog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.catalog')),
                ('discografica', models.CharField(max_length=100)),
                ('estil', models.CharField(max_length=100)),
                ('duracio', models.IntegerField()),
            ],
            bases=('app.catalog',),
        ),
        migrations.CreateModel(
            name='Dispositiu',
            fields=[
                ('catalog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.catalog')),
                ('modelo', models.CharField(default='', max_length=100)),
                ('serie', models.CharField(default='', max_length=100)),
            ],
            bases=('app.catalog',),
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('catalog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.catalog')),
                ('productora', models.CharField(max_length=100)),
                ('duracio', models.IntegerField()),
            ],
            bases=('app.catalog',),
        ),
        migrations.CreateModel(
            name='Llibre',
            fields=[
                ('catalog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.catalog')),
                ('CDU', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=13)),
                ('editorial', models.CharField(max_length=100)),
                ('collecio', models.CharField(max_length=100)),
                ('autor', models.CharField(default='', max_length=200)),
                ('pagines', models.IntegerField()),
            ],
            bases=('app.catalog',),
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('imatge', models.ImageField(blank=True, null=True, upload_to='imatges/')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('rol', models.CharField(blank=True, choices=[('Alumne', 'Alumne'), ('Admin', 'Admin'), ('Bibliotecari', 'Bibliotecari')], default='', max_length=50)),
                ('autentificacio', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='biblioteca_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='biblioteca_user_permissions', to='auth.permission')),
                ('centre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.centre')),
                ('cicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cicle')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', app.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estat', models.CharField(choices=[('Disponible', 'Disponible'), ('Prestat', 'Prestat'), ('Reservat', 'Reservat'), ('No disponible (només a la biblioteca)', 'No disponible (només a la biblioteca)')], max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('catalogo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='ImatgeCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imatge', models.ImageField(upload_to='static/')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Peticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol_peticio', models.CharField(max_length=100)),
                ('descripcio', models.TextField()),
                ('data_peticio', models.DateField(auto_now_add=True)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prestec', models.DateField(auto_now_add=True)),
                ('data_retorn', models.DateField(blank=True, null=True)),
                ('catalog', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.catalog')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(auto_now_add=True)),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exemplar')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElementCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.catalog')),
                ('tipus_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipusmaterial')),
            ],
        ),
    ]
