# Generated by Django 5.0.4 on 2024-05-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default='2002-11-07'),
            preserve_default=False,
        ),
    ]
