# Generated by Django 5.0.4 on 2024-05-02 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplar',
            name='catalogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.catalog'),
        ),
    ]
