# Generated by Django 5.0.4 on 2024-05-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_exemplar_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplar',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
