# Generated by Django 5.0.4 on 2024-04-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_nome_usuari_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='telefon',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
