# Generated by Django 5.0.4 on 2024-05-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_exemplar_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplar',
            name='element_catalog',
        ),
    ]
