# Generated by Django 5.0.4 on 2024-04-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuari_groups_alter_usuari_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuari',
            name='cognom',
        ),
        migrations.RemoveField(
            model_name='usuari',
            name='nom',
        ),
    ]
