# Generated by Django 5.0.4 on 2024-05-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_exemplar_element_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='estat',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Prestat', 'Prestat'), ('Reservat', 'Reservat'), ('No disponible (només a la biblioteca)', 'No disponible (només a la biblioteca)')], max_length=50),
        ),
    ]
