# Generated by Django 5.0.4 on 2024-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuari_grup_alter_usuari_groups_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuari',
            name='grup',
        ),
        migrations.AddField(
            model_name='usuari',
            name='rol',
            field=models.CharField(blank=True, choices=[('', 'Vacío'), ('Admin', 'Admin'), ('Bibliotecari', 'Bibliotecari')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='biblioteca_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='biblioteca_user_permissions', to='auth.permission'),
        ),
    ]
