# Generated by Django 5.0.4 on 2024-04-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_usuari_grup_usuari_rol_alter_usuari_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='rol',
            field=models.CharField(blank=True, choices=[('', 'Alumne'), ('Admin', 'Admin'), ('Bibliotecari', 'Bibliotecari')], default='', max_length=50),
        ),
    ]
