# Generated by Django 5.0.4 on 2024-04-26 16:34

import app.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usuari_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuari',
            managers=[
                ('objects', app.managers.UserManager()),
            ],
        ),
    ]
