# Generated by Django 5.0.4 on 2024-04-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_usuari_managers'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='cognom',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usuari',
            name='nom',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usuari',
            name='rol',
            field=models.CharField(blank=True, choices=[('Alumne', 'Alumne'), ('Admin', 'Admin'), ('Bibliotecari', 'Bibliotecari')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuari',
            name='telefon',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='biblioteca_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='biblioteca_user_permissions', to='auth.permission'),
        ),
    ]
