# Generated by Django 5.0.4 on 2024-04-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_usuari_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='rol',
            field=models.CharField(blank=True, choices=[('Alumne', 'Alumne'), ('Admin', 'Admin'), ('Bibliotecari', 'Bibliotecari')], default='', max_length=50),
        ),
    ]
