# Generated by Django 5.0.4 on 2024-04-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usuari_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='autentificacio',
            field=models.BooleanField(default=False),
        ),
    ]
