# Generated by Django 5.0.4 on 2024-04-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_usuari_cognom_usuari_nom_usuari_rol_usuari_telefon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuari',
            name='cognom',
        ),
        migrations.RemoveField(
            model_name='usuari',
            name='nom',
        ),
    ]
