# Generated by Django 5.0.4 on 2024-04-29 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_usuari_cognom_remove_usuari_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestec',
            name='exemplar',
        ),
        migrations.AddField(
            model_name='prestec',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.catalog'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='autentificacio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuari',
            name='cognom',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usuari',
            name='nom',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
