# Generated by Django 5.0.4 on 2024-04-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_usuari_autentificacio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestec',
            name='exemplar',
        ),
        migrations.AddField(
            model_name='prestec',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.catalog'),
        ),
    ]
