# Generated by Django 5.0.4 on 2024-04-29 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_prestec_exemplar_prestec_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='prestec',
            name='catalog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.catalog', to_field='nom'),
        ),
    ]
