# Generated by Django 5.0.4 on 2024-04-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_prestec_exemplar_prestec_catalog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuari',
            name='cognom',
        ),
        migrations.RemoveField(
            model_name='usuari',
            name='nom',
        ),
    ]
