# Generated by Django 5.0.4 on 2024-04-29 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_catalog_nom_alter_prestec_catalog'),
    ]

    operations = [
        migrations.AlterField(
        model_name='catalog',
        name='nom',
        field=models.CharField(max_length=100, unique=True),  # Asegúrate de añadir o mantener unique=True si estaba presente antes
    ),
        migrations.AlterField(
            model_name='prestec',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.catalog'),
        ),
    ]
