# Generated by Django 5.0.4 on 2024-04-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_catalog_nom_alter_prestec_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
