# Generated by Django 5.0.4 on 2024-04-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_catalog_cantidad'),
    ]

    operations = [
    ]
