# Generated by Django 5.0.4 on 2024-04-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20240430_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
