# Generated by Django 5.0.4 on 2024-04-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_catalog_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='br',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cd',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispositiu',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dvd',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llibre',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
